# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=234, max_length=40),
            preserve_default=False,
        ),
    ]
